export const READ_FOLLOWER_SUGGESTIONS_REQUEST =
  "READ_FOLLOWER_SUGGESTIONS_REQUEST";
export const READ_FOLLOWER_SUGGESTIONS_SUCCESS =
  "READ_FOLLOWER_SUGGESTIONS_SUCCESS";
export const READ_FOLLOWER_SUGGESTIONS_FAILURE =
  "READ_FOLLOWER_SUGGESTIONS_FAILURE";
export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAILURE = "FOLLOW_FAILURE";
export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAILURE = "UNFOLLOW_FAILURE";
