export const READ_FOLLOWER_SUGGESTIONS_REQUEST =
  "READ_FOLLOWER_SUGGESTIONS_REQUEST";
export const READ_FOLLOWER_SUGGESTIONS_SUCCESS =
  "READ_FOLLOWER_SUGGESTIONS_SUCCESS";
export const READ_FOLLOWER_SUGGESTIONS_FAILURE =
  "READ_FOLLOWER_SUGGESTIONS_FAILURE";
